options:
  tracadmin_user:
    type: string
    default: "Admin"
    description: "The Admin user for trac"
  tracadmin_pass:
    type: string
    default: "tracAdmin"
    description: "The Admin user password for trac"
  projectname:
    type: string
    default: "trac"
    description: "The trac project name"
  db_backend:
    type: string
    default: "mysql"
    description: "Backend database engine, possible values are 'sqlite' or 'mysql'"
