- name: create admin user
  htpasswd: path={{ trac_path }}.htpasswd name={{ tracadmin_user }} password={{ tracadmin_pass }} owner=root group=www-data mode=0640

- name: set admin permissions
  command: trac-admin {{ trac_path }} permission add {{ tracadmin_user }} TRAC_ADMIN

- name: set permissions
  file: path={{ trac_path }} owner=www-data state=directory

- name: configure apache
  template: src=templates/apache-trac.conf.in dest=/etc/apache2/sites-available/trac.conf owner=root group=root

- name: enable trac config
  file: src=/etc/apache2/sites-available/trac.conf dest=/etc/apache2/sites-enabled/trac.conf state=link

- name: enable mod python
  command: a2enmod python

- name: init trac env
  command: trac-admin {{ trac_path }} initenv {{projectname}} mysql://{{ database__user }}:{{ database__password }}@{{ database__private_address }}:3306/{{ database__database }} creates={{ trac_path }}/conf/trac.ini

