- hosts: all
  tasks:
    - name: install needed packages
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - trac
        - libapache2-mod-python
      tags:
        - install 
        - upgrade-charm

