- hosts: all
  tasks:
    - include: install.yml
      tags:
        - install
    - include: config-changed.yml
      tags:
          -config-changed
    - include: db-relation-changed.yml
      tags:
        - db-relation-changed
    - include: start.yml
      tags:
        - start
    - include: stop.yml
      tags:
        - stop
 handlers:
    - name: restart apache
      service: name=apache2 state=restarted
