- hosts: all
  vars:
    trac_basedir: /srv/trac
    trac_path: "{{ trac_basedir }}/{{ projectname }}"
  tasks:
    - include: install.yml
      tags:
        - install
    - include: config-changed.yml
      tags:
        - config-changed
    - include: database-relation-changed.yml
      tags:
        - database-relation-changed
    - include: start.yml
      tags:
        - start
    - include: stop.yml
      tags:
        - stop
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
